Update sphinx in requirements-docs.txt
Documentation build test was failing. Test is trying to build docs for matplotlib.
Matplotlib has required `sphinx>=1.8.1,!=2.0.0` since Dec. 18, 2020. 

Here's a snippet from the [full output](
https://github.com/bluesky/ophyd/pull/991/checks?check_run_id=2604828514)...

```
Exception occurred:
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 280, in setup
    app.add_css_file('plot_directive.css')
AttributeError: 'Sphinx' object has no attribute 'add_css_file'
```

References
---
* [Source code for matplotlib.sphinxext.plot_directive](
https://matplotlib.org/stable/_modules/matplotlib/sphinxext/plot_directive.html)
* [History for matplotlib/lib/matplotlib/sphinxext/plot_directive.py](
https://github.com/matplotlib/matplotlib/commits/f900c34799ea30e3c041902eee77c12694d65400/lib/matplotlib/sphinxext/plot_directive.py)
* [Tags for matplotlib](https://github.com/matplotlib/matplotlib/tags)

* [Sphinx.add_css_file](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file)
    * Added in v. 1.8
    * Not found in [v. 1.6 documentation](https://www.sphinx-doc.org/en/1.6.7/py-modindex.html)